"""Generate docs/agents.md and docs/messages.md from the code, so they never drift apart."""

from __future__ import annotations

from pathlib import Path

from kazner_agents.agents.specs import ALL_SPECS
from kazner_agents.labels import EntityType
from kazner_agents.messages import (
    PAYLOAD_TYPES,
    Decision,
    Envelope,
    Sentence,
    SentenceAnnotation,
    SentenceLabels,
    SentenceVerdict,
    Span,
)
from kazner_agents.orchestrator import ROUTES

HEADER = "<!-- Generated by `kna docs` from the code. Do not edit by hand. -->\n\n"


def agents_markdown() -> str:
    lines = [
        "# Agents",
        "",
        "Six agents plus the orchestrator (DESIGN.md section 4). Stage A2 = implemented now,",
        "A4 = planned for Assignment 4. Every agent has at most 5 tools.",
        "",
        "| Agent | Stage | Role | Input | Output | Tools | Done when |",
        "|---|---|---|---|---|---|---|",
    ]
    for spec in ALL_SPECS:
        tools = "; ".join(spec.tools)
        lines.append(
            f"| {spec.name} | {spec.stage} | {spec.role} | {spec.inputs} | {spec.outputs} "
            f"| {tools} | {spec.done_when} |"
        )
    return HEADER + "\n".join(lines) + "\n"


def type_name(annotation) -> str:
    if annotation is EntityType:
        return "EntityType (25 KazNERD types)"
    if isinstance(annotation, type):
        return annotation.__name__
    text = str(annotation)
    for prefix in ("kazner_agents.messages.", "typing.", "datetime."):
        text = text.replace(prefix, "")
    return text.replace("Union[", "union[")


def cell(text: str) -> str:
    """Escape '|' so that types like 'str | None' do not split a Markdown table cell."""
    return text.replace("|", r"\|")


def model_table(model) -> list[str]:
    lines = [f"### {model.__name__}", ""]
    if model.__doc__ and model.__doc__.strip():
        lines += [model.__doc__.strip().splitlines()[0], ""]
    lines += ["| Field | Type | Required | Description |", "|---|---|---|---|"]
    for name, info in model.model_fields.items():
        required = "yes" if info.is_required() else "no"
        description = info.description or ""
        field_type = cell(type_name(info.annotation))
        lines.append(f"| {name} | `{field_type}` | {required} | {description} |")
    return lines + [""]


def messages_markdown() -> str:
    lines = [
        "# Messages",
        "",
        "Every message is an `Envelope` around one payload (DESIGN.md section 5). All models are",
        "pydantic v2 and reject unknown fields.",
        "",
        "## Routing table",
        "",
        "| Payload | Recipient |",
        "|---|---|",
    ]
    lines += [f"| {payload} | {recipient} |" for payload, recipient in ROUTES.items()]
    lines += ["", "## Envelope", ""] + model_table(Envelope)
    lines += ["## Payloads", ""]
    for model in PAYLOAD_TYPES.values():
        lines += model_table(model)
    lines += ["## Building blocks", ""]
    for model in (Sentence, Span, SentenceAnnotation, SentenceLabels, Decision, SentenceVerdict):
        lines += model_table(model)
    return HEADER + "\n".join(lines).rstrip() + "\n"


def generated_docs(docs_dir: Path) -> dict[Path, str]:
    return {
        docs_dir / "agents.md": agents_markdown(),
        docs_dir / "messages.md": messages_markdown(),
    }


def write_docs(docs_dir: Path) -> list[Path]:
    docs_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for path, text in generated_docs(docs_dir).items():
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)
    return written


def outdated_docs(docs_dir: Path) -> list[Path]:
    return [
        path
        for path, text in generated_docs(docs_dir).items()
        if not path.exists() or path.read_text(encoding="utf-8") != text
    ]
